# File management

Responsible for reading data

In [2]:
from file_management import *
from helpers import *
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
ids, predictions, data, features = get_train_higgs_data()

In [4]:
ids.shape, predictions.shape, data.shape, features.shape

((250000, 1), (250000,), (250000, 30), (30,))

In [5]:
predictions

array([1, 0, 0, ..., 1, 0, 0])

In [7]:
df = pd.DataFrame(index=ids.flatten(), data=data, columns=features.flatten())
df['PRI_jet_num']

100000    2.0
100001    1.0
100002    1.0
100003    0.0
100004    0.0
         ... 
349995    0.0
349996    0.0
349997    1.0
349998    0.0
349999    0.0
Name: PRI_jet_num, Length: 250000, dtype: float64

In [13]:
df_NaN = df.replace(-999, np.NaN)
df_NaN

DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
100000       138.470                       51.655        97.827    27.980   
100001       160.937                       68.768       103.235    48.146   
100002           NaN                      162.172       125.953    35.635   
100003       143.905                       81.417        80.943     0.414   
100004       175.864                       16.915       134.805    16.405   
...              ...                          ...           ...       ...   
349995           NaN                       71.989        36.548     5.042   
349996           NaN                       58.179        68.083    22.439   
349997       105.457                       60.526        75.839    39.757   
349998        94.951                       19.362        68.812    13.504   
349999           NaN                       72.756        70.831     7.479   

        DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
100000                  0.91           124.711                2.666   
100001                   NaN               NaN                  NaN   
100002                   NaN               NaN                  NaN   
100003                   NaN               NaN                  NaN   
100004                   NaN               NaN                  NaN   
...                      ...               ...                  ...   
349995                   NaN               NaN                  NaN   
349996                   NaN               NaN                  NaN   
349997                   NaN               NaN                  NaN   
349998                   NaN               NaN                  NaN   
349999                   NaN               NaN                  NaN   

        DER_deltar_tau_lep  DER_pt_tot  DER_sum_pt  ...  PRI_met_phi  \
100000               3.064      41.928     197.760  ...       -0.277   
100001               3.473       2.078     125.157  ...       -1.916   
100002               3.148       9.336     197.814  ...       -2.186   
100003               3.310       0.414      75.968  ...        0.060   
100004               3.891      16.405      57.983  ...       -0.871   
...                    ...         ...         ...  ...          ...   
349995               1.392       5.042      55.892  ...        2.859   
349996               2.585      22.439      50.618  ...       -0.867   
349997               2.390      22.183     120.462  ...       -2.890   
349998               3.365      13.504      55.859  ...        0.811   
349999               2.025       7.479      83.240  ...       -1.596   

        PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
100000        258.733          2.0              67.435                2.150   
100001        164.546          1.0              46.226                0.725   
100002        260.414          1.0              44.251                2.053   
100003         86.062          0.0                 NaN                  NaN   
100004         53.131          0.0                 NaN                  NaN   
...               ...          ...                 ...                  ...   
349995        144.665          0.0                 NaN                  NaN   
349996         80.408          0.0                 NaN                  NaN   
349997        198.907          1.0              41.992                1.800   
349998        112.718          0.0                 NaN                  NaN   
349999         99.405          0.0                 NaN                  NaN   

        PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
100000                0.444                 46.062                    1.24   
100001                1.158                    NaN                     NaN   
100002               -2.028                    NaN                     NaN   
100003                  NaN                    NaN                     NaN   
100004                  Na

In [14]:
for column in df_NaN:
    nan_percent = (df_NaN[column].isna().sum() / df[column].count()) * 100
    if nan_percent > 0:
        print(column, ':' ,nan_percent)
        

DER_mass_MMC : 15.245600000000001
DER_deltaeta_jet_jet : 70.9828
DER_mass_jet_jet : 70.9828
DER_prodeta_jet_jet : 70.9828
DER_lep_eta_centrality : 70.9828
PRI_jet_leading_pt : 39.9652
PRI_jet_leading_eta : 39.9652
PRI_jet_leading_phi : 39.9652
PRI_jet_subleading_pt : 70.9828
PRI_jet_subleading_eta : 70.9828
PRI_jet_subleading_phi : 70.9828


In [15]:
df_no_nan = df_NaN.drop(['DER_deltaeta_jet_jet', 'DER_mass_jet_jet', 'DER_prodeta_jet_jet', 'DER_lep_eta_centrality', 'PRI_jet_subleading_pt', 'PRI_jet_subleading_eta', 'PRI_jet_subleading_phi'], axis=1)
df_no_nan.fillna(df.median(), inplace=True)
df_no_nan

DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
100000       138.470                       51.655        97.827    27.980   
100001       160.937                       68.768       103.235    48.146   
100002       105.012                      162.172       125.953    35.635   
100003       143.905                       81.417        80.943     0.414   
100004       175.864                       16.915       134.805    16.405   
...              ...                          ...           ...       ...   
349995       105.012                       71.989        36.548     5.042   
349996       105.012                       58.179        68.083    22.439   
349997       105.457                       60.526        75.839    39.757   
349998        94.951                       19.362        68.812    13.504   
349999       105.012                       72.756        70.831     7.479   

        DER_deltar_tau_lep  DER_pt_tot  DER_sum_pt  DER_pt_ratio_lep_tau  \
100000               3.064      41.928     197.760                 1.582   
100001               3.473       2.078     125.157                 0.879   
100002               3.148       9.336     197.814                 3.776   
100003               3.310       0.414      75.968                 2.354   
100004               3.891      16.405      57.983                 1.056   
...                    ...         ...         ...                   ...   
349995               1.392       5.042      55.892                 1.258   
349996               2.585      22.439      50.618                 1.162   
349997               2.390      22.183     120.462                 1.202   
349998               3.365      13.504      55.859                 0.999   
349999               2.025       7.479      83.240                 0.936   

        DER_met_phi_centrality  PRI_tau_pt  ...  PRI_lep_eta  PRI_lep_phi  \
100000                   1.396      32.638  ...        2.273       -2.414   
100001                   1.414      42.014  ...        0.501        0.103   
100002                   1.414      32.154  ...       -0.953        1.052   
100003                  -1.285      22.647  ...       -0.522       -3.100   
100004                  -1.385      28.209  ...        0.798        1.569   
...                        ...         ...  ...          ...          ...   
349995                  -1.414      24.754  ...       -0.950        0.380   
349996                  -1.345      23.416  ...        0.308        1.042   
349997                   0.529      35.636  ...        0.381        0.851   
349998                   1.414      27.944  ...       -0.874       -0.296   
349999                  -1.411      43.003  ...        1.490        0.637   

        PRI_met  PRI_met_phi  PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  \
100000   16.824       -0.277        258.733          2.0              67.435   
100001   44.704       -1.916        164.546          1.0              46.226   
100002   54.283       -2.186        260.414          1.0              44.251   
100003   31.082        0.060         86.062          0.0              38.960   
100004    2.723       -0.871         53.131          0.0              38.960   
...         ...          ...            ...          ...                 ...   
349995   46.520        2.859        144.665          0.0              38.960   
349996   46.737       -0.867         80.408          0.0              38.960   
349997   23.419       -2.890        198.907          1.0              41.992   
349998   12.150        0.811        112.718          0.0              38.960   
349999   40.729       -1.596         99.405          0.0              38.960   

        PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_all_pt  
100000                2.150                0.444         113.497  
100001                0.725                1.158          46.226  
100002                2.053               -2.028          44.251  
100003          

In [16]:
def ridge_regression(y, tx, lambda_):
    LAMBDA = 2 * len(y) * lambda_
    
    # Solve Normal Equations with Regularization Term
    w = np.linalg.solve((tx.T @ tx + (np.eye(len(tx[1])) * LAMBDA)), tx.T @ y)
    
    return w

In [17]:
def mse(y, x, w):
    err = y - x.dot(w)
    mse = err.dot(err) / (2 * len(y))

    return mse

In [18]:
lambdas = np.linspace(-100, 100, 1000)
x = df_no_nan.to_numpy()

Mse = []
for lambda_ in lambdas:
    w = ridge_regression(predictions, x, lambda_)
    mse_tr = mse(predictions, x, w)

    Mse.append(mse_tr)
    print(lambda_, ':', mse_tr)

    if mse_tr == 0.08912694822107427:
        break

-100.0 : 0.1721290173005223
-99.7997997997998 : 0.1732588839280406
-99.5995995995996 : 0.174428223046231
-99.3993993993994 : 0.1756387034282154
-99.1991991991992 : 0.17689208950969482
-98.998998998999 : 0.17819024793655613
-98.7987987987988 : 0.1795351546484386
-98.5985985985986 : 0.18092890254885918
-98.3983983983984 : 0.1823737098180941
-98.1981981981982 : 0.18387192893105786
-97.997997997998 : 0.18542605644936108
-97.7977977977978 : 0.18703874366450257
-97.5975975975976 : 0.1887128081777522
-97.3973973973974 : 0.19045124651233533
-97.1971971971972 : 0.19225724786439127
-96.996996996997 : 0.19413420911199888
-96.7967967967968 : 0.19608575121566688
-96.5965965965966 : 0.19811573715977696
-96.3963963963964 : 0.20022829160315345
-96.1961961961962 : 0.20242782242741464
-95.995995995996 : 0.20471904439604252
-95.7957957957958 : 0.20710700516402525
-95.5955955955956 : 0.20959711390938277
-95.3953953953954 : 0.2121951728934209
-95.1951951951952 : 0.21490741229791246
-94.994994994995 : 0.217

In [19]:
np.min(Mse)

0.08920820758090521

In [20]:
lambda_ = 0.10010010010010717

w = ridge_regression(predictions, x, lambda_)
w

array([ 4.45996061e-04, -4.19758202e-03, -2.53554493e-03, -6.82376549e-04,
        1.16177553e-01, -5.97442432e-04,  2.38033649e-03, -2.41402218e-02,
        4.90804094e-02,  3.44991656e-03, -3.93657714e-04, -3.07693002e-04,
        1.92250028e-03, -3.96304559e-04,  9.53873760e-04,  2.03422111e-03,
        3.84189602e-04, -1.15274015e-04,  3.90102710e-02,  4.86685288e-04,
        7.45423398e-04,  9.58712866e-04, -2.98978229e-03])

In [21]:
ids_t, predictions_t, data_t, features_t = get_test_higgs_data()

In [23]:
df_t = pd.DataFrame(index=ids_t.flatten(), data=data_t, columns=features_t.flatten())
df_t.replace(-999, np.NaN)
df_no_nan_t = df_t.drop(['DER_deltaeta_jet_jet', 'DER_mass_jet_jet', 'DER_prodeta_jet_jet', 'DER_lep_eta_centrality', 'PRI_jet_subleading_pt', 'PRI_jet_subleading_eta', 'PRI_jet_subleading_phi'], axis=1)
df_no_nan_t.fillna(df.median(), inplace=True)
x_t = df_no_nan_t.to_numpy()


In [24]:
pred = x_t @ w

In [25]:
pred[pred < 0.5] = -1
pred[pred >= 0.5] = 1


In [26]:
unique, counts = np.unique(pred, return_counts=True)
unique, counts

(array([-1.,  1.]), array([465560, 102678]))

In [28]:
create_csv_submission(ids_t, pred, 'prediction_2')